#ifndef _RESOURCE_MANAGER_H_
#define _RESOURCE_MANAGER_H_

#include "backend/logger.h"
#include "backend/registry.h"
#include "runtime/camera/core.h"
#include "runtime/light/core.h"
#include "runtime/light/list.h"
#include "runtime/mesh/core.h"
#include "runtime/pipeline/compute.h"
#include "runtime/pipeline/render.h"
#include "runtime/probe/reflection/grid.h"
#include "runtime/probe/reflection/plane.h"
#include "runtime/probe/reflection/probe.h"
#include "runtime/scene/core.h"
#include "runtime/shader/core.h"
#include "runtime/texture/core.h"
#include "utils/defines.h"
#include "utils/hsht.h"
#include "webgpu/webgpu.h"
#include <stddef.h>

typedef enum {
  REMStatus_Success,
  REMStatus_MaxCapacity,
  REMStatus_AllocFail,
  REMStatus_NullResource,
  REMStatus_UnfoundResource,
  REMStatus_ProtectedResource,
  REMStatus_UndefError,
} REMStatus;

#define REM_TYPE_COUNT 20
typedef enum {
  REMType_Texture,
  REMType_View,
  REMType_ShaderModule,
  REMType_Buffer,
  REMType_Sampler,
  REMType_Mbin,
  REMType_Gltf,
  REMType_Scene,
  REMType_Mesh,
  REMType_Camera,
  REMType_RenderPipeline,
  REMType_ComputePipeline,
  REMType_Shader,
  REMType_PointLight,
  REMType_AmbientLight,
  REMType_SpotLight,
  REMType_SunLight,
  REMType_PlaneReflection,
  REMType_ProbeReflection,
  REMType_ProbeReflectionGrid,
} REMType;

#define REM_STRUCT_ITEM(Name, Handle)                                          \
  typedef struct {                                                             \
    reg_id_t owner;                                                            \
    uint32_t key;                                                              \
    REMType type;                                                              \
    bool occupied;                                                             \
    Handle handle;                                                             \
  } REM##Name;

REM_STRUCT_ITEM(Texture, WGPUTexture);
REM_STRUCT_ITEM(View, WGPUTextureView);
REM_STRUCT_ITEM(Buffer, WGPUBuffer);
REM_STRUCT_ITEM(ShaderModule, WGPUShaderModule);
REM_STRUCT_ITEM(Sampler, WGPUSampler);

REM_STRUCT_ITEM(Mesh, Mesh);
REM_STRUCT_ITEM(Scene, Scene);
REM_STRUCT_ITEM(RenderPipeline, RenderPipeline);
REM_STRUCT_ITEM(ComputePipeline, ComputePipeline);
REM_STRUCT_ITEM(Shader, Shader);
REM_STRUCT_ITEM(Camera, Camera);

REM_STRUCT_ITEM(PointLight, PointLight);
REM_STRUCT_ITEM(AmbientLight, AmbientLight);
REM_STRUCT_ITEM(SpotLight, SpotLight);
REM_STRUCT_ITEM(SunLight, SunLight);

REM_STRUCT_ITEM(ProbeReflection, ProbeReflection);
REM_STRUCT_ITEM(PlaneReflection, ProbeReflectionPlane);
REM_STRUCT_ITEM(ProbeReflectionGrid, ProbeReflectionGrid);

REM_STRUCT_ITEM(Gltf, const char *);
REM_STRUCT_ITEM(Mbin, const char *);

REM_STRUCT_ITEM(Void, void *);

/* TODO:
Add the following entities ?
 - sem lists
 - sem

 make sure the remove their respective item->id = ....
 */
typedef struct ResourceManager {

  HashTable entries[REM_TYPE_COUNT];

} ResourceManager;

extern ResourceManager g_rem;

/*
  Hash utils callback

  In order to improve access to our resources O(1), we use a hash system.
  However we use two kinds of hash methods depending on the resource type:
  1. WGPU related resources used Opaque Pointers, as a result we use this
  pointer to generate the hash.
  2. Engine related resources (Mesh, Scene...) have an ID generated by the
  register. As a result we use this ID  to generate the hash.

  In the same way that both WGPU and Engine resources use their respective
  constructor (wgpuDeviceCreate.... vs item_create()) and destructor
  (wgpuResourceRelease() vs item_destroy())
 */
uint32_t rem_generate_ptr_hash(const void *);
uint32_t rem_generate_id_hash(const void *);
void rem_bucket_set_occupied(const void *, const bool);
bool rem_bucket_get_occupied(const void *);
bool rem_bucket_compare(const void *, const void *);

static const struct {
  const char *label;
  const size_t capacity;
  const size_t type_size;
  hsht_hash_generator hash_generator;
} rem_config[] = {
    [REMType_Texture] =
        {
            .label = "Texture",
            .capacity = 997,
            .type_size = sizeof(REMTexture),
            .hash_generator = rem_generate_ptr_hash,
        },
    [REMType_View] =
        {
            .label = "View",
            .capacity = 997,
            .type_size = sizeof(REMView),
            .hash_generator = rem_generate_ptr_hash,
        },
    [REMType_ShaderModule] =
        {
            .label = "Shader Module",
            .capacity = 127,
            .type_size = sizeof(REMShaderModule),
            .hash_generator = rem_generate_ptr_hash,
        },
    [REMType_Buffer] =
        {
            .label = "Buffer",
            .capacity = 997,
            .type_size = sizeof(REMBuffer),
            .hash_generator = rem_generate_ptr_hash,
        },
    [REMType_Sampler] =
        {
            .label = "Sampler",
            .capacity = 127,
            .type_size = sizeof(REMShaderModule),
            .hash_generator = rem_generate_ptr_hash,
        },
    /*

      ==== ID BASED ====

     */
    [REMType_Mbin] =
        {
            .label = "Mbin",
            .capacity = 61,
            .type_size = sizeof(REMMbin),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_Gltf] =
        {
            .label = "Gltf",
            .capacity = 61,
            .type_size = sizeof(REMGltf),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_Scene] =
        {
            .label = "Scene",
            .capacity = 1,
            .type_size = sizeof(REMScene),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_Mesh] =
        {
            .label = "Mesh",
            .capacity = 127,
            .type_size = sizeof(REMMesh),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_RenderPipeline] =
        {
            .label = "Render Pipeline",
            .capacity = 71,
            .type_size = sizeof(REMRenderPipeline),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_ComputePipeline] =
        {
            .label = "Compute Pipeline",
            .capacity = 31,
            .type_size = sizeof(REMComputePipeline),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_Shader] =
        {
            .label = "Shader",
            .capacity = 127,
            .type_size = sizeof(REMShader),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_Camera] =
        {
            .label = "Camera",
            .capacity = 31,
            .type_size = sizeof(REMCamera),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_PointLight] =
        {
            .label = "Point Light",
            .capacity = 37,
            .type_size = sizeof(REMPointLight),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_AmbientLight] =
        {
            .label = "Ambient Light",
            .capacity = 37,
            .type_size = sizeof(REMAmbientLight),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_SpotLight] =
        {
            .label = "Spot Light",
            .capacity = 37,
            .type_size = sizeof(REMSpotLight),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_SunLight] =
        {
            .label = "Sun Light",
            .capacity = 37,
            .type_size = sizeof(REMSunLight),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_PlaneReflection] =
        {
            .label = "Plane Reflection",
            .capacity = 17,
            .type_size = sizeof(REMPlaneReflection),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_ProbeReflection] =
        {
            .label = "Probe Reflection",
            .capacity = 17,
            .type_size = sizeof(REMProbeReflection),
            .hash_generator = rem_generate_id_hash,
        },
    [REMType_ProbeReflectionGrid] =
        {
            .label = "Probe Reflection Grid",
            .capacity = 17,
            .type_size = sizeof(REMProbeReflectionGrid),
            .hash_generator = rem_generate_id_hash,
        },
};

typedef enum {
  REMWriteFlag_None = 0,
  REMWriteFlag_FreeData = 1 << 0,
  REMWriteFlag_STBIFreeData = 1 << 1,
} REMWriteFlag;

EXTERN_C_BEGIN

REMStatus resource_manager_init();

WGPUTexture rem_new_texture(const WGPUTextureDescriptor *);

WGPUTextureView rem_new_view(const WGPUTexture,
                             const WGPUTextureViewDescriptor *);

WGPUBuffer rem_new_buffer(const WGPUBufferDescriptor *);

WGPUSampler rem_new_sampler(const WGPUSamplerDescriptor *);

WGPUShaderModule rem_new_shader_module(char *code, const char *label,
                                       const REMWriteFlag);

REMStatus rem_write_buffer(WGPUBuffer, const size_t, void *, const size_t,
                           const REMWriteFlag);
REMStatus rem_write_texture(WGPUTexture, void *, const size_t,
                            const TextureChannel, const size_t,
                            const REMWriteFlag);

Mesh *rem_new_mesh();
Scene *rem_new_scene();
Shader *rem_new_shader();
Camera *rem_new_camera();
RenderPipeline *rem_new_render_pipeline();
ComputePipeline *rem_new_compute_pipeline();

PointLight *rem_new_point_light();
AmbientLight *rem_new_ambient_light();
SpotLight *rem_new_spot_light();
SunLight *rem_new_sun_light();

ProbeReflectionPlane *rem_new_plane_reflection();
ProbeReflection *rem_new_probe_reflection();
ProbeReflectionGrid *rem_new_probe_reflection_grid();

REMStatus rem_destroy_texture(WGPUTexture *);
REMStatus rem_destroy_sampler(WGPUSampler *);
REMStatus rem_destroy_view(WGPUTextureView *);
REMStatus rem_destroy_buffer(WGPUBuffer *);
REMStatus rem_destroy_shader_module(WGPUShaderModule *);

REMStatus rem_destroy_shader(Shader *);
REMStatus rem_destroy_mesh(Mesh *);
REMStatus rem_destroy_scene(Scene *);
REMStatus rem_destroy_render_pipeline(RenderPipeline *);
REMStatus rem_destroy_compute_pipeline(ComputePipeline *);

REMStatus rem_destroy_mbin(const char *);
REMStatus rem_destroy_gltf(const char *);

REMStatus rem_destroy_point_light(PointLight *);
REMStatus rem_destroy_ambient_light(AmbientLight *);
REMStatus rem_destroy_sun_light(SunLight *);
REMStatus rem_destroy_spot_light(SpotLight *);

REMStatus rem_destroy_plane_reflection(ProbeReflectionPlane *);
REMStatus rem_destroy_probe_reflection(ProbeReflection *);
REMStatus rem_destroy_probe_reflection_grid(ProbeReflectionGrid *);

EXTERN_C_END

#endif
